language: python
python: ["3.8"]
install:
  - pip install pipenv
  - pipenv install --ignore-pipfile --dev
script:
  - pipenv run pytest --cov-report=xml --cov=src
after_success:
  - bash <(curl -s https://codecov.io/bash)
